# Generated by Django 4.1.4 on 2023-02-06 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome_produto', models.CharField(max_length=100)),
                ('Descricao', models.TextField()),
                ('Quantidade', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=100)),
                ('Preco', models.DecimalField(decimal_places=2, max_digits=100)),
                ('Quantidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Estoque.estoque')),
            ],
        ),
    ]
