# Generated by Django 4.1.4 on 2023-02-08 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estoque', '0002_estoque_preco_delete_produto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa_lucro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome_do_produto', models.CharField(max_length=100)),
                ('Valor', models.DecimalField(decimal_places=2, max_digits=100)),
                ('Data', models.DateField(verbose_name='%d-%m-%y')),
            ],
        ),
    ]
