# Generated by Django 4.1.4 on 2023-02-08 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estoque', '0004_alter_empresa_lucro_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa_lucro',
            name='Data',
            field=models.DateField(verbose_name='/%d/%m/%Y'),
        ),
    ]
