# Generated by Django 4.1.4 on 2023-03-24 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estoque', '0008_estoque_img_alter_empresa_lucro_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa_lucro',
            name='Valor',
            field=models.DecimalField(decimal_places=2, max_digits=1000),
        ),
    ]
