# Generated by Django 4.1.4 on 2023-10-28 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estoque', '0011_alter_clientes_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='Endereco',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='Produto',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
